export interface MonitoringSite {
  id: number;
  nameCn: string;
  nameEn: string;
  longitude: number;
  latitude: number;
  region: string;
  // Detail fields
  elevationM?: number;
  speciesEn?: string;
  speciesCn?: string;
  climateCn?: string;
  climateEn?: string;
  instrumentsEn?: string[];
  instrumentsCn?: string[];
  partnerEn?: string;
  partnerCn?: string;
  established?: number;
  descriptionEn?: string;
  descriptionCn?: string;
}

export const monitoringSites: MonitoringSite[] = [
  {
    id: 1, nameCn: "美国华盛顿", nameEn: "Washington, USA",
    longitude: -122.85, latitude: 46.04, region: "International",
    elevationM: 120, speciesEn: "Populus trichocarpa", speciesCn: "毛果杨",
    climateEn: "Marine West Coast (Cfb)", climateCn: "温带海洋性气候",
    instrumentsEn: ["TDP Sap Flow Probes", "Point Dendrometers", "Meteo Station"],
    instrumentsCn: ["TDP液流探针", "点式径向生长仪", "气象站"],
    partnerEn: "Washington State University", partnerCn: "华盛顿州立大学",
    established: 2019,
    descriptionEn: "Comparative study site for Populus trichocarpa water relations in a Pacific Northwest maritime climate, collaborating with WSU.",
    descriptionCn: "太平洋西北海洋性气候下毛果杨水分关系的对比研究站点，与华盛顿州立大学合作。",
  },
  {
    id: 2, nameCn: "河南温县", nameEn: "Wen County, Henan",
    longitude: 113.14, latitude: 34.90, region: "Central China",
    elevationM: 110, speciesEn: "Populus × euramericana", speciesCn: "欧美杨",
    climateEn: "Warm Temperate Continental Monsoon", climateCn: "暖温带大陆性季风气候",
    instrumentsEn: ["TDP Sap Flow Probes", "Band Dendrometers", "Soil Moisture Sensors"],
    instrumentsCn: ["TDP液流探针", "环式径向生长仪", "土壤水分传感器"],
    partnerEn: "Beijing Forestry University", partnerCn: "北京林业大学",
    established: 2012,
    descriptionEn: "Long-term monitoring of poplar plantation water use in the Yellow River floodplain, a key site for understanding irrigation impacts.",
    descriptionCn: "黄河冲积平原杨树人工林水分利用长期监测站，研究灌溉对林分水分的影响。",
  },
  {
    id: 3, nameCn: "河北威县", nameEn: "Wei County, Hebei",
    longitude: 115.27, latitude: 37.06, region: "North China",
    elevationM: 35, speciesEn: "Populus × euramericana", speciesCn: "欧美杨",
    climateEn: "Warm Temperate Semi-humid Monsoon", climateCn: "暖温带半湿润季风气候",
    instrumentsEn: ["TDP Sap Flow Probes", "Point Dendrometers", "Meteo Station"],
    instrumentsCn: ["TDP液流探针", "点式径向生长仪", "气象站"],
    partnerEn: "Beijing Forestry University", partnerCn: "北京林业大学",
    established: 2013,
    descriptionEn: "North China Plain poplar plantation site studying sap flow scaling and water balance in a semi-humid agricultural landscape.",
    descriptionCn: "华北平原杨树人工林站点，研究半湿润农业景观中的液流尺度扩展和水量平衡。",
  },
  {
    id: 4, nameCn: "宁夏中卫", nameEn: "Zhongwei, Ningxia",
    longitude: 105.50, latitude: 37.35, region: "Northwest",
    elevationM: 1250, speciesEn: "Populus simonii", speciesCn: "小叶杨",
    climateEn: "Temperate Continental Arid", climateCn: "温带大陆性干旱气候",
    instrumentsEn: ["HFD Sap Flow Probes", "Point Dendrometers", "Soil Moisture Sensors"],
    instrumentsCn: ["HFD液流探针", "点式径向生长仪", "土壤水分传感器"],
    partnerEn: "Ningxia University", partnerCn: "宁夏大学",
    established: 2016,
    descriptionEn: "Desert-edge shelterbelt site monitoring Populus simonii water stress and hydraulic redistribution under extreme aridity.",
    descriptionCn: "荒漠边缘防护林站点，监测极端干旱条件下小叶杨的水分胁迫和水力再分配。",
  },
  {
    id: 5, nameCn: "青海西宁", nameEn: "Xining, Qinghai",
    longitude: 101.62, latitude: 36.68, region: "Northwest",
    elevationM: 2260, speciesEn: "Populus cathayana", speciesCn: "青杨",
    climateEn: "Plateau Continental", climateCn: "高原大陆性气候",
    instrumentsEn: ["TDP Sap Flow Probes", "Band Dendrometers", "Meteo Station"],
    instrumentsCn: ["TDP液流探针", "环式径向生长仪", "气象站"],
    partnerEn: "Qinghai University", partnerCn: "青海大学",
    established: 2018,
    descriptionEn: "High-altitude plateau site studying Populus cathayana adaptation to cold-dry conditions and UV stress.",
    descriptionCn: "高海拔高原站点，研究青杨对寒冷干燥条件和紫外线胁迫的适应。",
  },
  {
    id: 6, nameCn: "甘肃张掖", nameEn: "Zhangye, Gansu",
    longitude: 100.58, latitude: 38.93, region: "Northwest",
    elevationM: 1480, speciesEn: "Populus gansuensis", speciesCn: "甘肃杨",
    climateEn: "Temperate Continental Arid", climateCn: "温带大陆性干旱气候",
    instrumentsEn: ["TDP Sap Flow Probes", "Point Dendrometers", "Eddy Covariance Tower"],
    instrumentsCn: ["TDP液流探针", "点式径向生长仪", "涡度相关通量塔"],
    partnerEn: "Gansu Agricultural University", partnerCn: "甘肃农业大学",
    established: 2015,
    descriptionEn: "Hexi Corridor oasis plantation site with eddy covariance, studying water-carbon coupling in irrigated poplar stands.",
    descriptionCn: "河西走廊绿洲人工林站点，配备涡度相关系统，研究灌溉杨树林的水碳耦合。",
  },
  {
    id: 7, nameCn: "陕西杨凌", nameEn: "Yangling, Shaanxi",
    longitude: 108.28, latitude: 34.19, region: "Northwest",
    elevationM: 520, speciesEn: "Populus × tomentosa", speciesCn: "毛白杨",
    climateEn: "Warm Temperate Semi-humid", climateCn: "暖温带半湿润气候",
    instrumentsEn: ["TDP Sap Flow Probes", "Band Dendrometers", "Stable Isotope Sampling"],
    instrumentsCn: ["TDP液流探针", "环式径向生长仪", "稳定同位素采样"],
    partnerEn: "Northwest A&F University", partnerCn: "西北农林科技大学",
    established: 2014,
    descriptionEn: "Guanzhong Plain site combining sap flow and stable isotope analysis to trace water sources in Populus tomentosa plantations.",
    descriptionCn: "关中平原站点，结合液流和稳定同位素分析追踪毛白杨人工林水分来源。",
  },
  {
    id: 8, nameCn: "山东莘县", nameEn: "Shenxian, Shandong",
    longitude: 115.50, latitude: 36.32, region: "North China",
    elevationM: 40, speciesEn: "Populus × euramericana", speciesCn: "欧美杨",
    climateEn: "Warm Temperate Semi-humid Monsoon", climateCn: "暖温带半湿润季风气候",
    instrumentsEn: ["TDP Sap Flow Probes", "Point Dendrometers", "Soil Moisture Sensors"],
    instrumentsCn: ["TDP液流探针", "点式径向生长仪", "土壤水分传感器"],
    partnerEn: "Shandong Agricultural University", partnerCn: "山东农业大学",
    established: 2013,
    descriptionEn: "Yellow River Basin agricultural-forestry interface site studying poplar water consumption and groundwater interactions.",
    descriptionCn: "黄河流域农林交错带站点，研究杨树耗水量与地下水相互作用。",
  },
  {
    id: 9, nameCn: "山东利津", nameEn: "Lijin, Shandong",
    longitude: 118.29, latitude: 37.58, region: "North China",
    elevationM: 8, speciesEn: "Populus × euramericana, Tamarix chinensis", speciesCn: "欧美杨、柽柳",
    climateEn: "Warm Temperate Semi-humid Monsoon", climateCn: "暖温带半湿润季风气候",
    instrumentsEn: ["TDP Sap Flow Probes", "Point Dendrometers", "Soil Salinity Sensors"],
    instrumentsCn: ["TDP液流探针", "点式径向生长仪", "土壤盐分传感器"],
    partnerEn: "Beijing Forestry University", partnerCn: "北京林业大学",
    established: 2014,
    descriptionEn: "Yellow River Delta saline-alkali site monitoring salt-tolerant species water relations and coastal shelterbelt ecology.",
    descriptionCn: "黄河三角洲盐碱地站点，监测耐盐树种水分关系和沿海防护林生态。",
  },
  {
    id: 10, nameCn: "甘肃天水", nameEn: "Tianshui, Gansu",
    longitude: 105.91, latitude: 34.55, region: "Northwest",
    elevationM: 1100, speciesEn: "Populus × tomentosa, Robinia pseudoacacia", speciesCn: "毛白杨、刺槐",
    climateEn: "Warm Temperate Semi-arid", climateCn: "暖温带半干旱气候",
    instrumentsEn: ["TDP Sap Flow Probes", "Band Dendrometers", "Meteo Station"],
    instrumentsCn: ["TDP液流探针", "环式径向生长仪", "气象站"],
    partnerEn: "Gansu Forestry Technological College", partnerCn: "甘肃林业职业技术学院",
    established: 2017,
    descriptionEn: "Loess Plateau transition zone site studying mixed plantation water use strategies and soil conservation benefits.",
    descriptionCn: "黄土高原过渡带站点，研究混交林水分利用策略和水土保持效益。",
  },
  {
    id: 11, nameCn: "山西祁县", nameEn: "Qi County, Shanxi",
    longitude: 112.42, latitude: 37.26, region: "North China",
    elevationM: 780, speciesEn: "Populus × tomentosa", speciesCn: "毛白杨",
    climateEn: "Warm Temperate Continental Semi-arid", climateCn: "暖温带大陆性半干旱气候",
    instrumentsEn: ["HFD Sap Flow Probes", "Point Dendrometers", "Soil Moisture Sensors"],
    instrumentsCn: ["HFD液流探针", "点式径向生长仪", "土壤水分传感器"],
    partnerEn: "Shanxi Agricultural University", partnerCn: "山西农业大学",
    established: 2015,
    descriptionEn: "Fen River valley site monitoring Populus tomentosa hydraulic architecture and drought responses on the Loess Plateau margin.",
    descriptionCn: "汾河谷地站点，监测黄土高原边缘毛白杨的水力结构和干旱响应。",
  },
  {
    id: 12, nameCn: "山东高唐", nameEn: "Gaotang, Shandong",
    longitude: 116.10, latitude: 36.81, region: "North China",
    elevationM: 30, speciesEn: "Populus × euramericana", speciesCn: "欧美杨",
    climateEn: "Warm Temperate Semi-humid Monsoon", climateCn: "暖温带半湿润季风气候",
    instrumentsEn: ["TDP Sap Flow Probes", "Band Dendrometers", "Meteo Station"],
    instrumentsCn: ["TDP液流探针", "环式径向生长仪", "气象站"],
    partnerEn: "Beijing Forestry University", partnerCn: "北京林业大学",
    established: 2012,
    descriptionEn: "One of the earliest CP-GPE Net sites, providing over a decade of continuous sap flow data from North China Plain poplar plantations.",
    descriptionCn: "CP-GPE Net最早的站点之一，提供超过十年的华北平原杨树人工林连续液流数据。",
  },
  {
    id: 13, nameCn: "北京通州", nameEn: "Tongzhou, Beijing",
    longitude: 116.75, latitude: 39.73, region: "North China",
    elevationM: 25, speciesEn: "Populus × tomentosa, Salix matsudana", speciesCn: "毛白杨、旱柳",
    climateEn: "Warm Temperate Semi-humid Monsoon", climateCn: "暖温带半湿润季风气候",
    instrumentsEn: ["TDP Sap Flow Probes", "HFD Sap Flow Probes", "Point Dendrometers", "Eddy Covariance Tower"],
    instrumentsCn: ["TDP液流探针", "HFD液流探针", "点式径向生长仪", "涡度相关通量塔"],
    partnerEn: "Beijing Forestry University", partnerCn: "北京林业大学",
    established: 2010,
    descriptionEn: "Flagship site near Beijing with comprehensive instrumentation including eddy covariance, serving as the network's primary calibration and training center.",
    descriptionCn: "北京近郊旗舰站点，配备涡度相关等综合仪器，是网络的主要标定和培训中心。",
  },
  {
    id: 14, nameCn: "辽宁新民", nameEn: "Xinmin, Liaoning",
    longitude: 122.75, latitude: 42.01, region: "Northeast",
    elevationM: 45, speciesEn: "Populus × xiaohei", speciesCn: "小黑杨",
    climateEn: "Temperate Continental Monsoon", climateCn: "温带大陆性季风气候",
    instrumentsEn: ["TDP Sap Flow Probes", "Band Dendrometers", "Soil Moisture Sensors"],
    instrumentsCn: ["TDP液流探针", "环式径向生长仪", "土壤水分传感器"],
    partnerEn: "Shenyang Agricultural University", partnerCn: "沈阳农业大学",
    established: 2016,
    descriptionEn: "Northeast China Three-North Shelterbelt site monitoring cold-hardy poplar species water relations and frost-drought interactions.",
    descriptionCn: "东北三北防护林站点，监测耐寒杨树品种的水分关系和冻旱交互作用。",
  },
  {
    id: 15, nameCn: "黑龙江齐齐哈尔", nameEn: "Qiqihar, Heilongjiang",
    longitude: 124.22, latitude: 47.58, region: "Northeast",
    elevationM: 150, speciesEn: "Populus simonii × P. nigra", speciesCn: "小叶杨×黑杨",
    climateEn: "Temperate Continental", climateCn: "温带大陆性气候",
    instrumentsEn: ["TDP Sap Flow Probes", "Point Dendrometers", "Meteo Station"],
    instrumentsCn: ["TDP液流探针", "点式径向生长仪", "气象站"],
    partnerEn: "Northeast Forestry University", partnerCn: "东北林业大学",
    established: 2017,
    descriptionEn: "Northernmost site in the network, studying poplar hybrid water use under extreme continental climate with harsh winters.",
    descriptionCn: "网络最北端站点，研究极端大陆性气候和严冬条件下杨树杂交种的水分利用。",
  },
  {
    id: 16, nameCn: "吉林白城", nameEn: "Baicheng, Jilin",
    longitude: 122.84, latitude: 45.81, region: "Northeast",
    elevationM: 160, speciesEn: "Populus × xiaozhannica", speciesCn: "小钻杨",
    climateEn: "Temperate Continental Semi-arid", climateCn: "温带大陆性半干旱气候",
    instrumentsEn: ["TDP Sap Flow Probes", "Band Dendrometers", "Soil Moisture Sensors"],
    instrumentsCn: ["TDP液流探针", "环式径向生长仪", "土壤水分传感器"],
    partnerEn: "Jilin Agricultural University", partnerCn: "吉林农业大学",
    established: 2018,
    descriptionEn: "Horqin Sandy Land edge site studying shelterbelt poplar water consumption and desertification control effectiveness.",
    descriptionCn: "科尔沁沙地边缘站点，研究防护林杨树耗水量和防沙治沙效果。",
  },
  {
    id: 17, nameCn: "河南南阳", nameEn: "Nanyang, Henan",
    longitude: 112.62, latitude: 33.05, region: "Central China",
    elevationM: 130, speciesEn: "Populus × euramericana", speciesCn: "欧美杨",
    climateEn: "Subtropical-Warm Temperate Transition", climateCn: "亚热带-暖温带过渡气候",
    instrumentsEn: ["TDP Sap Flow Probes", "Point Dendrometers", "Meteo Station"],
    instrumentsCn: ["TDP液流探针", "点式径向生长仪", "气象站"],
    partnerEn: "Henan Agricultural University", partnerCn: "河南农业大学",
    established: 2019,
    descriptionEn: "Subtropical-temperate transition zone site studying poplar growth responses to monsoon variability and summer heat stress.",
    descriptionCn: "亚热带-温带过渡带站点，研究杨树对季风变异和夏季高温胁迫的生长响应。",
  },
  {
    id: 18, nameCn: "内蒙古达拉特", nameEn: "Dalate, Inner Mongolia",
    longitude: 109.85, latitude: 40.37, region: "North China",
    elevationM: 1020, speciesEn: "Populus simonii", speciesCn: "小叶杨",
    climateEn: "Temperate Continental Semi-arid", climateCn: "温带大陆性半干旱气候",
    instrumentsEn: ["HFD Sap Flow Probes", "Point Dendrometers", "Soil Moisture Sensors"],
    instrumentsCn: ["HFD液流探针", "点式径向生长仪", "土壤水分传感器"],
    partnerEn: "Inner Mongolia Agricultural University", partnerCn: "内蒙古农业大学",
    established: 2020,
    descriptionEn: "Kubuqi Desert northern edge site monitoring shelterbelt poplar survival and water use under severe drought and sand burial.",
    descriptionCn: "库布齐沙漠北缘站点，监测严重干旱和沙埋条件下防护林杨树的存活和水分利用。",
  },
  {
    id: 19, nameCn: "内蒙古磴口县", nameEn: "Dengkou, Inner Mongolia",
    longitude: 106.77, latitude: 40.48, region: "North China",
    elevationM: 1050, speciesEn: "Populus × gansuensis, Haloxylon ammodendron", speciesCn: "甘肃杨、梭梭",
    climateEn: "Temperate Continental Arid", climateCn: "温带大陆性干旱气候",
    instrumentsEn: ["TDP Sap Flow Probes", "Heat Ratio Probes", "Point Dendrometers"],
    instrumentsCn: ["TDP液流探针", "热比率探针", "点式径向生长仪"],
    partnerEn: "Chinese Academy of Forestry", partnerCn: "中国林业科学研究院",
    established: 2019,
    descriptionEn: "Ulan Buh Desert edge site comparing water use strategies between poplar plantations and native xerophytic shrubs.",
    descriptionCn: "乌兰布和沙漠边缘站点，比较杨树人工林和本地旱生灌木的水分利用策略。",
  },
  {
    id: 20, nameCn: "江苏宿迁", nameEn: "Suqian, Jiangsu",
    longitude: 118.31, latitude: 33.33, region: "East China",
    elevationM: 20, speciesEn: "Populus × euramericana", speciesCn: "欧美杨",
    climateEn: "Subtropical Humid Monsoon", climateCn: "亚热带湿润季风气候",
    instrumentsEn: ["TDP Sap Flow Probes", "Band Dendrometers", "Meteo Station"],
    instrumentsCn: ["TDP液流探针", "环式径向生长仪", "气象站"],
    partnerEn: "Nanjing Forestry University", partnerCn: "南京林业大学",
    established: 2020,
    descriptionEn: "East China humid zone site studying high-yield poplar plantation water-carbon dynamics under ample water supply conditions.",
    descriptionCn: "华东湿润区站点，研究充足水分条件下速生杨树人工林的水碳动态。",
  },
  {
    id: 21, nameCn: "新疆伊犁", nameEn: "Ili, Xinjiang",
    longitude: 80.84, latitude: 43.99, region: "Northwest",
    elevationM: 680, speciesEn: "Populus euphratica", speciesCn: "胡杨",
    climateEn: "Temperate Continental Semi-arid", climateCn: "温带大陆性半干旱气候",
    instrumentsEn: ["TDP Sap Flow Probes", "Point Dendrometers", "Groundwater Level Sensors"],
    instrumentsCn: ["TDP液流探针", "点式径向生长仪", "地下水位传感器"],
    partnerEn: "Xinjiang Agricultural University", partnerCn: "新疆农业大学",
    established: 2021,
    descriptionEn: "Westernmost site monitoring the iconic Populus euphratica (desert poplar) water relations and groundwater dependency in the Ili River valley.",
    descriptionCn: "最西端站点，监测伊犁河谷标志性胡杨的水分关系和地下水依赖性。",
  },
  {
    id: 22, nameCn: "河南济源", nameEn: "Jiyuan, Henan",
    longitude: 112.45, latitude: 35.04, region: "Central China",
    elevationM: 250, speciesEn: "Populus × tomentosa, Paulownia fortunei", speciesCn: "毛白杨、泡桐",
    climateEn: "Warm Temperate Semi-humid Monsoon", climateCn: "暖温带半湿润季风气候",
    instrumentsEn: ["TDP Sap Flow Probes", "HFD Sap Flow Probes", "Band Dendrometers", "Stable Isotope Sampling"],
    instrumentsCn: ["TDP液流探针", "HFD液流探针", "环式径向生长仪", "稳定同位素采样"],
    partnerEn: "Beijing Forestry University", partnerCn: "北京林业大学",
    established: 2022,
    descriptionEn: "Newest site at the southern Taihang Mountains foothills, studying mixed poplar-paulownia agroforestry water partitioning.",
    descriptionCn: "太行山南麓最新站点，研究杨树-泡桐混合农林系统的水分分配。",
  },
];

export const regions = [
  "All",
  "China",
  "North China",
  "Northeast",
  "Northwest",
  "Central China",
  "East China",
  "International",
];

export const regionsCn: Record<string, string> = {
  "All": "全部",
  "China": "中国",
  "North China": "华北",
  "Northeast": "东北",
  "Northwest": "西北",
  "Central China": "华中",
  "East China": "华东",
  "International": "国际",
};

export const stats = [
  { labelEn: "Monitoring Sites", labelCn: "监测站点", value: 22 },
  { labelEn: "Species Monitored", labelCn: "监测树种", value: 12, suffix: "+" },
  { labelEn: "Years of Data", labelCn: "数据年限", value: 15, suffix: "+" },
  { labelEn: "International Partners", labelCn: "国际合作", value: 1, suffix: "" },
];

// Simplified Yellow River Basin boundary polygon (lat/lng pairs)
export const yellowRiverBasinCoords: [number, number][] = [
  [35.5, 96.0],
  [36.0, 97.5],
  [36.5, 99.0],
  [37.0, 100.0],
  [37.5, 101.0],
  [37.8, 102.5],
  [38.0, 103.5],
  [38.5, 104.5],
  [39.0, 105.5],
  [39.5, 106.5],
  [40.0, 107.0],
  [40.5, 108.0],
  [40.8, 109.0],
  [40.5, 110.0],
  [40.0, 110.5],
  [39.5, 111.0],
  [39.0, 111.5],
  [38.5, 112.0],
  [38.0, 112.5],
  [37.5, 113.0],
  [37.0, 113.5],
  [36.5, 114.0],
  [36.0, 115.0],
  [35.8, 116.0],
  [36.0, 117.0],
  [37.0, 118.0],
  [37.5, 118.5],
  [38.0, 119.0],
  // Return south
  [37.0, 119.0],
  [36.0, 118.0],
  [35.0, 117.0],
  [34.5, 116.0],
  [34.0, 115.0],
  [33.5, 114.0],
  [33.5, 113.0],
  [33.8, 112.0],
  [34.0, 111.0],
  [34.2, 110.0],
  [34.5, 109.0],
  [34.8, 108.0],
  [35.0, 107.0],
  [35.0, 106.0],
  [35.0, 105.0],
  [34.8, 104.0],
  [34.5, 103.0],
  [34.2, 102.0],
  [34.0, 101.0],
  [34.0, 100.0],
  [34.5, 99.0],
  [35.0, 97.5],
  [35.5, 96.0],
];
